name: livery Updates

on:
  push:
    paths:
      - livery.json
  workflow_dispatch:

jobs:
  send:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install deps
        run: pip install -r .webhook/requirements.txt

      - name: Run script
        env:
          LIVERYUPDATES: ${{ secrets.LIVERYUPDATES }}
        run: python3 .webhook/livery_update.py

      - name: Save commit
        run: |
          mkdir -p .webhook
          echo "${{ github.sha }}" > .webhook/commit.txt

      - name: Commit and push commit.txt
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add .webhook/commit.txt
          git commit -m "update commit.txt" || echo "no changes"
          git push
